import nx from "@nx/eslint-plugin";

// Repo-wide `no-restricted-imports` paths, keyed so individual libs can compose
// their own narrowly-scoped exceptions (see actor-context-transport) instead of
// blanket-disabling the rule. New restrictions added here flow into every
// project automatically, including those that opt out of a *different* entry.
export const restrictedImportPaths = {
  // Internal CLS populator + raw CLS keys live in the `@bge/actor-context`
  // barrel so the bundler inlines them, but only entry-point interceptors and
  // worker bases may use them. Application code and plugins must use the
  // read-only `AuditContextService` — this enforces "plugins have read-only
  // access to CLS actor; cannot forge" (issue #57).
  auditContextInternal: {
    name: "@bge/actor-context",
    importNames: [
      "AuditContextInternalService",
      "ACTOR_CLS_KEY",
      "CORRELATION_ID_CLS_KEY",
      "LOCALE_CLS_KEY",
      "SOURCE_CLS_KEY"
    ],
    message:
      "Internal CLS populator/keys. Entry-point interceptors and worker bases only — application and plugin code must use the read-only AuditContextService (issue #57)."
  }
};

// #145: CI guardrail against NEW hardcoded user-facing strings in libs already
// migrated by #144. These `no-restricted-syntax` selectors flag string/template
// literals passed to a `*Exception(...)` constructor or used as a `message:`
// value — both must instead carry a catalog key via `t()` (exceptions / success
// bodies) or `i18nValidationMessage()` (validators). Opt-in PER LIB: a migrated
// lib's own `eslint.config.mjs` imports this array into a `no-restricted-syntax`
// rule scoped to its source, so the guardrail grows as #144 lands lib-by-lib and
// never red-CIs a lib that hasn't been migrated yet. Genuinely non-user-facing
// cases use an explicit `// eslint-disable-next-line no-restricted-syntax --
// <reason>` escape hatch. `raw=/^['"]/` restricts to STRING literals (a numeric
// status code as an exception arg is not flagged); namespaced callees
// (`ns.FooException`) are a known gap — call sites here import exceptions directly.
export const i18nHardcodedStringSelectors = [
  {
    selector: "NewExpression[callee.name=/Exception$/] > Literal[raw=/^['\"]/]",
    message:
      "Hardcoded user-facing string in an exception. Use a catalog key: throw new NotFoundException(t('errors.…', { … })). (#144/#145)",
  },
  {
    selector: "NewExpression[callee.name=/Exception$/] > TemplateLiteral",
    message:
      "Hardcoded user-facing template string in an exception. Move the copy to a catalog key and interpolate via t('errors.…', { … }). (#144/#145)",
  },
  {
    selector: "Property[key.name='message'] > Literal[raw=/^['\"]/]",
    message:
      "Hardcoded user-facing `message:` string. Use a catalog key: t('success.…') for response bodies or i18nValidationMessage('validation.…') on validators. (#144/#145)",
  },
  {
    selector: "Property[key.name='message'] > TemplateLiteral",
    message:
      "Hardcoded user-facing `message:` template string. Move the copy to a catalog key and interpolate via t('…', { … }). (#144/#145)",
  },
];

export default [
  ...nx.configs["flat/base"],
  ...nx.configs["flat/typescript"],
  ...nx.configs["flat/javascript"],
  {
    ignores: [
      "**/dist",
      "**/out-tsc",
      // Generated by the nestjs-i18n CLI (`npm run i18n:generate`). Carries its
      // own `/* eslint-disable */`; ignore it here so the unused-disable-directive
      // rule doesn't warn on the generated header.
      "**/i18n.generated.ts"
    ]
  },
  {
    files: [
      "**/*.ts",
      "**/*.tsx",
      "**/*.js",
      "**/*.jsx"
    ],
    rules: {
      "@nx/enforce-module-boundaries": [
        "error",
        {
          enforceBuildableLibDependency: true,
          allow: [
            "^.*/eslint(\\.base)?\\.config\\.[cm]?[jt]s$"
          ],
          depConstraints: [
            {
              sourceTag: "*",
              onlyDependOnLibsWithTags: [
                "*"
              ]
            }
          ]
        }
      ]
    }
  },
  {
    files: [
      "**/*.ts",
      "**/*.tsx",
      "**/*.cts",
      "**/*.mts",
      "**/*.js",
      "**/*.jsx",
      "**/*.cjs",
      "**/*.mjs"
    ],
    // Override or add rules here
    rules: {
      "no-restricted-imports": [
        "error",
        { paths: Object.values(restrictedImportPaths) }
      ]
    }
  }
];
