import type { I18nPath } from './generated/i18n.generated';

/**
 * Serializable discriminator marking an object as a deferred translation. A
 * plain string-keyed property (never a `Symbol`, which `JSON.stringify` drops)
 * so the mark survives a JSON round-trip: on the success path a marker embedded
 * in a response body is stored in the Valkey response cache and later rehydrated
 * as a prototype-less object, so {@link isI18nMessage} must recognize it
 * structurally rather than via `instanceof`.
 */
const I18N_MESSAGE_BRAND = '__i18nMessage';

/**
 * A deferred translation: a catalog key plus its interpolation args, carried
 * from a call site to the edge without translating there. Services stay
 * decoupled from `I18nService` — they only name a key. The
 * `I18nExceptionFilter` (error path) and `I18nResponseInterceptor` (success
 * path) resolve it against the request's locale.
 *
 * `key` is typed as `I18nPath` (generated by `npm run i18n:generate`), so an
 * invalid key fails `tsc`.
 */
export class I18nMessage {
  /** @see {@link I18N_MESSAGE_BRAND} — makes markers survive a cache round-trip. */
  readonly [I18N_MESSAGE_BRAND] = true;

  constructor(
    readonly key: I18nPath,
    readonly args?: Record<string, unknown>,
  ) {}
}

/**
 * A marker's `message` names its key and args, as
 * `errors.gateway_registry.auth_type_not_implemented {"authType":"Bearer"}`, or
 * the key alone when it has no args. Nest reads a body's string `message` into
 * the exception's own, so a marker thrown where no edge translates it (a
 * worker, a gRPC server) still says which refusal it was in `error.message`,
 * the stack and anything that stores them, instead of only the class name
 * (#501).
 *
 * It lives on the prototype, where `JSON.stringify`, the response cache's
 * serializer, spread and `structuredClone` all skip it, so a marker serializes
 * as its brand, key and args and nothing else. It is defined here rather than
 * as a class getter only to keep it off the type: `isI18nMessage` narrows a
 * rehydrated plain object to `I18nMessage`, and that object has no `message`.
 *
 * It runs inside the exception's constructor and must never throw, or a
 * BigInt or circular arg would replace the intended status with a TypeError.
 */
Object.defineProperty(I18nMessage.prototype, 'message', {
  get(this: I18nMessage): string {
    let args: string | undefined;
    try {
      args = JSON.stringify(this.args);
    } catch {
      return `${this.key} [unserializable args]`;
    }
    return args === undefined || args === '{}' ? this.key : `${this.key} ${args}`;
  },
});

/**
 * Marks an error message for edge translation. Pass the result straight to any
 * standard Nest HTTP exception — the exception type still supplies the status
 * code, and `I18nExceptionFilter` translates the key/args:
 *
 * ```ts
 * throw new NotFoundException(t('errors.language.not_found', { id }));
 * ```
 *
 * Nest stores the returned object as the exception's response body verbatim, so
 * the filter recovers the exact `I18nMessage` instance (same-process reference,
 * no serialization in between). Where no filter runs, the exception's `message`
 * names the key and args instead.
 */
export function t(key: I18nPath, args?: Record<string, unknown>): I18nMessage {
  return new I18nMessage(key, args);
}

/**
 * True when a value is a deferred `t()` translation. Tests the serializable
 * brand rather than `instanceof` so a marker is still recognized after a JSON
 * round-trip through the response cache (a cache hit rehydrates it as a
 * prototype-less plain object).
 *
 * Requires an *own* brand set to `true` and a string `key` — the `key` is
 * dereferenced downstream (`translate(value.key, …)`), so validating it here
 * keeps a bare `{ key }`, an inherited brand, or an unrelated object that merely
 * carries `__i18nMessage` from being mistaken for a marker.
 */
export function isI18nMessage(value: unknown): value is I18nMessage {
  if (typeof value !== 'object' || value === null) {
    return false;
  }
  const record = value as Record<string, unknown>;
  return (
    Object.prototype.hasOwnProperty.call(record, I18N_MESSAGE_BRAND) &&
    record[I18N_MESSAGE_BRAND] === true &&
    typeof record.key === 'string'
  );
}
