export { ClsLocaleResolver } from './lib/cls-locale.resolver';
// Generated by `npm run i18n:generate` (nestjs-i18n CLI) from the `en` catalog.
// Re-exported so consumers type `I18nContext<I18nTranslations>`, `t()`, and
// `i18nValidationMessage<I18nTranslations>(...)` against real keys — invalid
// keys then fail `tsc`. Regenerate after editing any catalog; CI drift-checks it.
export type { I18nPath, I18nTranslations } from './lib/generated/i18n.generated';
export { I18nConfigModule } from './lib/i18n.module';
export { I18nExceptionFilter } from './lib/i18n-exception.filter';
export { I18nResponseInterceptor } from './lib/i18n-response.interceptor';
export { LocaleResolutionService, type LocaleResolutionInput } from './lib/locale-resolution.service';
export { FALLBACK_LOCALE } from './lib/locale.constants';
export { SupportedLocalesService } from './lib/supported-locales.service';
export { translateException } from './lib/translate-exception';
export { I18nMessage, isI18nMessage, t } from './lib/translatable';
export { i18nValidationMessage, type I18nValidationPath } from './lib/validation-message';
