import type { I18nPath } from './generated/i18n.generated';

/**
 * A deferred translation: a catalog key plus its interpolation args, carried
 * from a call site to the edge without translating there. Services stay
 * decoupled from `I18nService` — they only name a key. The
 * `I18nExceptionFilter` resolves it against the request's locale.
 *
 * `key` is typed as `I18nPath` (generated by `npm run i18n:generate`), so an
 * invalid key fails `tsc`.
 */
export class I18nMessage {
  constructor(
    readonly key: I18nPath,
    readonly args?: Record<string, unknown>,
  ) {}
}

/**
 * Marks an error message for edge translation. Pass the result straight to any
 * standard Nest HTTP exception — the exception type still supplies the status
 * code, and `I18nExceptionFilter` translates the key/args:
 *
 * ```ts
 * throw new NotFoundException(t('errors.language.not_found', { id }));
 * ```
 *
 * Nest stores the returned object as the exception's response body verbatim, so
 * the filter recovers the exact `I18nMessage` instance (same-process reference,
 * no serialization in between).
 */
export function t(key: I18nPath, args?: Record<string, unknown>): I18nMessage {
  return new I18nMessage(key, args);
}

/** True when an exception's response body is a deferred `t()` translation. */
export function isI18nMessage(value: unknown): value is I18nMessage {
  return value instanceof I18nMessage;
}
