name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - run: npm ci
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: master

      - run: npm run db:generate
      - run: npm run proto:generate

      - run: npx nx run-many -t typecheck
      - run: npx nx affected -t test --parallel --maxParallel=3 --passWithNoTests
      - run: npx nx affected -t lint build --parallel --maxParallel=3

      - run: npx nx fix-ci
        if: always()
